trigger: none

pool:
  name: Lab
  demands:
    - Agent.OS -equals Linux

resources:
  repositories:
    - repository: template
      name: DevOps/Template
      type: git
  pipelines:
    - pipeline: package
      source: ngxtw-package
      trigger: true

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    - group: ngxtw-master
  - ${{ elseif eq(variables['Build.SourceBranchName'], 'next') }}:
    - group: ngxtw-next
  - ${{ elseif eq(variables['Build.SourceBranchName'], 'release') }}:
    - group: ngxtw-release
  - ${{ else }}:
    - group: ngxtw-dev

stages:
  - stage: CI
    jobs:
      - template: lab/ngxtw/docs/job.build.yml@template

  - stage: CD
    dependsOn: CI
    pool:
      name: Lab
      demands:
        - Agent.OS -equals Linux
        - AZP_RUNS -equals docs
    jobs:
      - template: lab/ngxtw/docs/job.release.yml@template
