trigger:
  branches:
    include:
      - master
      - next
      - release/*
  paths:
    include:
      - projects/lib/src/*

pool:
  name: Lab
  demands:
    - Agent.OS -equals Linux

resources:
  repositories:
    - repository: template
      name: DevOps/Template
      type: git

parameters:
  - name: RunTests
    type: boolean
    default: true
  - name: RunBuild
    type: boolean
    default: true
  - name: RunSetup
    type: boolean
    default: true

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - group: ngxtw-master
  - ${{ elseif eq(variables['Build.SourceBranchName'], 'next') }}:
      - group: ngxtw-next
  - ${{ elseif eq(variables['Build.SourceBranchName'], 'release') }}:
      - group: ngxtw-release
  - ${{ else }}:
      - group: ngxtw-dev
  - name: Patch
    value: $[counter(variables.MajorMinor, 0)]

name: $(Build.DefinitionName)-v${{variables.Release}}

stages:
  - stage: CI
    jobs:
      - template: lab/ngxtw/package/job.build-test-publish.yml@template
        parameters:
          RunTests: ${{parameters.RunTests}}
          RunBuild: ${{parameters.RunBuild}}
          RunSetup: ${{parameters.RunSetup}}

  - stage: CD
    dependsOn: CI
    jobs:
      - template: lab/ngxtw/package/job.release.yml@template
