trigger: none

pool:
  name: Lab
  demands:
    - Agent.OS -equals Linux

resources:
  repositories:
    - repository: template
      name: DevOps/Template
      type: git
  pipelines:
    - pipeline: lib
      source: ngx-tailwind-ui
      trigger: true

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    - group: ngx-tailwind-master
  - ${{ elseif eq(variables['Build.SourceBranchName'], 'next') }}:
    - group: ngx-tailwind-next
  - ${{ elseif eq(variables['Build.SourceBranchName'], 'release') }}:
    - group: ngx-tailwind-release
  - ${{ else }}:
    - group: ngx-tailwind-dev

stages:
  - stage: CI
    jobs:
      - template: ngx-tailwind/job.build-app.yml@template

  - stage: CD
    dependsOn: CI
    jobs:
      - template: ngx-tailwind/job.release-app.yml@template
