trigger:
  paths:
    include:
      - projects/ngxtw-ui/src/*

pool:
  name: Lab
  demands:
    - Agent.OS -equals Linux

resources:
  repositories:
    - repository: template
      name: DevOps/Template
      type: git

parameters:
  - name: RunSetup
    type: boolean
    default: true
  - name: RunBuild
    type: boolean
    default: true
  - name: RunTests
    type: boolean
    default: true

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - group: ngxtw-master
  - ${{ elseif eq(variables['Build.SourceBranchName'], 'next') }}:
      - group: ngxtw-next
  - ${{ elseif eq(variables['Build.SourceBranchName'], 'release') }}:
      - group: ngxtw-release
  - ${{ else }}:
      - group: ngxtw-dev
  - name: Patch
    value: $[counter(variables.MajorMinor, 0)]

stages:
  - stage: CI
    jobs:
      - template: ngxtw/job.build-test-publish.yml@template
        parameters:
          ProjetName: ngxtw-ui
          RunSetup: ${{parameters.RunSetup}}
          RunBuild: ${{parameters.RunBuild}}
          RunTests: ${{parameters.RunTests}}

  - stage: CD
    dependsOn: CI
    jobs:
      - template: ngxtw/job.release-lib.yml@template
